# Generated by Django 5.2.4 on 2025-07-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bengaluru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=25)),
                (
                    "job_title",
                    models.CharField(
                        choices=[
                            ("Developer", "Developer"),
                            ("Manager", "Manager"),
                            ("Asst.Manager", "Asst.Manager"),
                            ("HR", "HR"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sal", models.FloatField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("Bsc", "Bsc"),
                            ("M.Tech", "M.Tech"),
                            ("B.Tech", "B.Tech"),
                            ("Msc", "Msc"),
                        ],
                        max_length=10,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Mumbai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=25)),
                (
                    "job_title",
                    models.CharField(
                        choices=[
                            ("Developer", "Developer"),
                            ("Manager", "Manager"),
                            ("Asst.Manager", "Asst.Manager"),
                            ("HR", "HR"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sal", models.FloatField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("Bsc", "Bsc"),
                            ("M.Tech", "M.Tech"),
                            ("B.Tech", "B.Tech"),
                            ("Msc", "Msc"),
                        ],
                        max_length=10,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Pune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=25)),
                (
                    "job_title",
                    models.CharField(
                        choices=[
                            ("Developer", "Developer"),
                            ("Manager", "Manager"),
                            ("Asst.Manager", "Asst.Manager"),
                            ("HR", "HR"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sal", models.FloatField()),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("Bsc", "Bsc"),
                            ("M.Tech", "M.Tech"),
                            ("B.Tech", "B.Tech"),
                            ("Msc", "Msc"),
                        ],
                        max_length=10,
                    ),
                ),
                ("joining_date", models.DateField()),
                ("location", models.CharField(max_length=25)),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
